### ISSUE TITLE
Fails to update and skips the update

### ISSUE THREAD

**Issue by dawiinci** [saniho/apiNetatmo#2]
```
Logger: custom_components.apiNetatmo.sensor
Source: custom_components/apiNetatmo/sensor.py:75
Integration: apiNetatmo ([documentation](https://github.com/saniho/apiNetatmo)) 

update fait, last synchro ... 
```

Maybe a retry function would help in that case.

**Comment by saniho** [comment]
I have generate the pre release 1.0.2.0, if you can check and confirmed that's ok

**Comment by dawiinci** [comment]
It works properly. 

However, according to the history it is not clear if you skip or retry. If you retry (e.g. every minute), this will be perfect.

Thanks for the quick fixes btw.

**Comment by dawiinci** [comment]
One minor issue I saw in your latest pre-release:

rain has the unit %, whereas it should be mm (or mm/h, I think).

**Comment by saniho** [comment]
Do you want to contribute to this project ?

**Comment by dawiinci** [comment]
I'm just a user, but I will test your releases and report issues, if there are any.

Regarding the rain gauge, there is one for mm (rain right now), which is what you implemented already (right?) and there is one for mm/h and mm/d. 

When do you plan to release the next public version?

**Comment by saniho** [comment]
the update is done every 3 minutes
